### PR TITLE
Fix package name and bump version.

### LINKED ISSUE #1: PyPI repo typo
There is a typo in the PyPI repository for the project, it is listed as 'xontib-kitty' (not xontrib).
README points to the 'right' name which doesn't work.

### PR DESCRIPTION
**Pull request by gotgenes**
This fixes #1.

Might want to remove the misnamed package from PyPI, too.

### CODE REVIEW

**Comment by gotgenes** [comment]
@scopatz Ping. 🙂

**Comment by scopatz** [comment]
Whoops Sorry! Don't know how I wasn't following this repo!

**Comment by scopatz** [comment]
BTW, version numbers are bumped by rever: https://regro.github.io/rever-docs/

**Comment by scopatz** [comment]
Should be all fixed up now!

**Comment by gotgenes** [comment]
Thank you!

**Pull request merged**
